import { TestPages } from '../../../lib';
import { AccountTransferPage } from './AccountTransferPage';
import { LVTPaymentPage } from "./LVTPaymentPage";
import { AutoPayPaymentPage } from './AutoPayPaymentPage';
import { PaymentViaPartnerBankPage } from "./PaymentViaPartnerBankPage";
import { TransferCentersPage } from "./TransferCenterPage";
import { TelegraphicTransferPage } from "./TelegraphicTransferPage";
import { IntraCompanyTransferPage } from "./IntraCompanyTransferPage";
import { FastPaymentPage } from "./FastPaymentPage";
import { SGPayNowPage } from "./SGPayNowPage";
import { PayrollPage } from "./PayrollPage";
import { NewFastCollectionPage } from "./NewFastCollectionPage";
import { BulkCollectionPage } from "./BulkCollectionPage";
import { BulkPaymentPage } from "./BulkPaymentPage";
import { MEPSPaymentPage } from "./MEPSPaymentPage";
import { NewBillPaymentPage } from "./NewBillPaymentPage";
import { PaymentTemplatesPage } from "./PaymentTemplatesPage";
import { BeneficiaryPage } from "./BeneficiaryPage";
import { CrossBoarderACHPage } from "./CrossBoarderACHPage";
import { HVTPaymentPage } from "./HVTPaymentPage";
import { CNAPSPaymentPage } from "./CNAPSPaymentPage";
import { HKCHATSPaymentPage } from "./HKCHATSPaymentPage";
import { FPSPaymentPage } from "./FPSPaymentPage";
import { RTGSPaymentPage } from "./RTGSPaymentPage";
import { SKNPaymentPage } from "./SKNPaymentPage";
import { ITTPage } from "./ITTPage";
import { NEFTPaymentPage } from "./NEFTPaymentPage";
import { FixedDepositPlacementPage } from "./FixedDepositPlacementPage";
import { FixedDepositMVP2Page } from "./FixedDepositMVP2Page";
import { PartnerBankPaymentPage } from "./PartnerBankPaymentPage";
import { TWACHBulkPaymentPage } from "./TWACHBulkPaymentPage";
import { CustomPaymentPage } from './CustomPaymentPage';
import { VNTaxPaymentPage } from "./VNTaxPaymentPage";
import { VNLvtPage } from "./VNLvtPage";
import { TWFISCPaymentPage } from "./TWFISCPaymentPage";
import { PaymentLimit } from "./PaymentLimit";
import { ChequePaymentPage } from "./ChequePaymentPage";
import { DemandDraftPaymentPage } from "./DemandDraftPaymentPage";
import { MT101PaymentPage } from "./MT101PaymentPage";
import { ETAXPaymentPage } from "./ETAXPaymentPage";
import { SelectApproverPage } from "./SelectApproverPage";
import { StopChequePage } from "./StopChequePage";
import { GiroPaymentPage } from "./GiroPaymentPage";
import { IMPSPaymentPage } from "./IMPSPaymentPage";
import { BIFASTPaymentPage} from "./BIFASTPaymentPage";
import { RecurringPaymentPage} from "./RecurringPaymentPage";
import { SinglePaymentPage} from "./SinglePaymentPage_reskin";
import { eACHPaymentPage} from "./eACHPaymentPage";
import { IDTAXPaymentPage } from './idTaxPaymentPage';
import { IBPSPaymentPage} from  './IBPSPaymentPage';
import { RTOLPaymentPage} from  './RTOLPaymentPage';
import { IDBIFASTRequestPage} from  './IDBIFASTRequestPage';

export {
    AccountTransferPage, LVTPaymentPage, AutoPayPaymentPage, PaymentViaPartnerBankPage,TransferCentersPage,ETAXPaymentPage, TelegraphicTransferPage, IntraCompanyTransferPage, FastPaymentPage, SGPayNowPage, PayrollPage, NewFastCollectionPage, BulkCollectionPage, BulkPaymentPage, MEPSPaymentPage, NewBillPaymentPage, PaymentTemplatesPage, CrossBoarderACHPage, HVTPaymentPage, CNAPSPaymentPage, HKCHATSPaymentPage, FPSPaymentPage, RTGSPaymentPage, SKNPaymentPage, ITTPage, NEFTPaymentPage, FixedDepositPlacementPage, FixedDepositMVP2Page, PartnerBankPaymentPage, TWACHBulkPaymentPage, CustomPaymentPage, VNTaxPaymentPage, VNLvtPage, TWFISCPaymentPage, PaymentLimit, ChequePaymentPage, DemandDraftPaymentPage, MT101PaymentPage, SelectApproverPage, StopChequePage, GiroPaymentPage,IMPSPaymentPage,BIFASTPaymentPage,RecurringPaymentPage,SinglePaymentPage,eACHPaymentPage,IBPSPaymentPage,RTOLPaymentPage,IDBIFASTRequestPage
};

export class PaymentsPages extends TestPages {
    public AccountTransferPage: AccountTransferPage;
    public TransferCentersPage: TransferCentersPage;
    public LVTPaymentPage: LVTPaymentPage;
    public AutoPayPaymentPage: AutoPayPaymentPage;
    public PaymentViaPartnerBankPage: PaymentViaPartnerBankPage;
    public TelegraphicTransferPage: TelegraphicTransferPage;
    public IntraCompanyTransferPage: IntraCompanyTransferPage;
    public FastPaymentPage: FastPaymentPage;
    public ETAXPaymentPage: ETAXPaymentPage;
    public SGPayNowPage: SGPayNowPage;
    public PayrollPage: PayrollPage;
    public NewFastCollectionPage: NewFastCollectionPage;
    public BulkCollectionPage: BulkCollectionPage;
    public BulkPaymentPage: BulkPaymentPage;
    public MEPSPaymentPage: MEPSPaymentPage;
    public NewBillPaymentPage: NewBillPaymentPage;
    public PaymentTemplatesPage: PaymentTemplatesPage;
    public BeneficiaryPage: BeneficiaryPage;
    public CrossBoarderACHPage: CrossBoarderACHPage;
    public HVTPaymentPage: HVTPaymentPage;
    public CNAPSPaymentPage: CNAPSPaymentPage;
    public HKCHATSPaymentPage: HKCHATSPaymentPage;
    public FPSPaymentPage: FPSPaymentPage;
    public RTGSPaymentPage: RTGSPaymentPage;
    public SKNPaymentPage: SKNPaymentPage;
    public ITTPage: ITTPage;
    public NEFTPaymentPage: NEFTPaymentPage;
    public FixedDepositPlacementPage: FixedDepositPlacementPage;
    public FixedDepositMVP2Page: FixedDepositMVP2Page;
    public PartnerBankPaymentPage: PartnerBankPaymentPage;
    public TWACHPaymentPage: TWACHBulkPaymentPage;
    public TWFISCPaymentPage: TWFISCPaymentPage;
    public CustomPaymentPage: CustomPaymentPage;
    public VNTaxPaymentPage: VNTaxPaymentPage;
    public VNLvtPage: VNLvtPage;
    public PaymentLimit: PaymentLimit;
    public chequePaymentPage: ChequePaymentPage;
    public demandDraftPaymentPage: DemandDraftPaymentPage;
    public mt101PaymentPage: MT101PaymentPage;
    public selectApproverPage: SelectApproverPage;
    public stopChequePage: StopChequePage;
    public giroPaymentPage: GiroPaymentPage;
    public IMPSPaymentPage:IMPSPaymentPage;
    public BIFASTPaymentPage:BIFASTPaymentPage;
    public RecurringPaymentPage : RecurringPaymentPage;
    public singlePaymentPage:SinglePaymentPage;
    public eACHPaymentPage:eACHPaymentPage;
    public IDTAXPaymentPage:IDTAXPaymentPage;
    public IBPSPaymentPage : IBPSPaymentPage;
    public RTOLPaymentPage : RTOLPaymentPage;
    public IDBIFASTRequestPage : IDBIFASTRequestPage;

    constructor() {
        super();
        this.AccountTransferPage = new AccountTransferPage();
        this.LVTPaymentPage = new LVTPaymentPage();
        this.AutoPayPaymentPage = new AutoPayPaymentPage();
        this.PaymentViaPartnerBankPage = new PaymentViaPartnerBankPage();
        this.TransferCentersPage = new TransferCentersPage();
        this.TelegraphicTransferPage = new TelegraphicTransferPage();
        this.IntraCompanyTransferPage = new IntraCompanyTransferPage();
        this.FastPaymentPage = new FastPaymentPage();
        this.SGPayNowPage = new SGPayNowPage();
        this.PayrollPage = new PayrollPage();
        this.ETAXPaymentPage = new ETAXPaymentPage();
        this.NewFastCollectionPage = new NewFastCollectionPage();
        this.BulkCollectionPage = new BulkCollectionPage();
        this.BulkPaymentPage = new BulkPaymentPage();
        this.MEPSPaymentPage = new MEPSPaymentPage();
        this.NewBillPaymentPage = new NewBillPaymentPage();
        this.PaymentTemplatesPage = new PaymentTemplatesPage();
        this.BeneficiaryPage = new BeneficiaryPage();
        this.CrossBoarderACHPage = new CrossBoarderACHPage();
        this.HVTPaymentPage = new HVTPaymentPage();
        this.CNAPSPaymentPage = new CNAPSPaymentPage();
        this.HKCHATSPaymentPage = new HKCHATSPaymentPage();
        this.FPSPaymentPage = new FPSPaymentPage();
        this.RTGSPaymentPage = new RTGSPaymentPage();
        this.SKNPaymentPage = new SKNPaymentPage();
        this.ITTPage = new ITTPage();
        this.NEFTPaymentPage = new NEFTPaymentPage();
        this.FixedDepositPlacementPage = new FixedDepositPlacementPage();
        this.FixedDepositMVP2Page = new FixedDepositMVP2Page();
        this.PartnerBankPaymentPage = new PartnerBankPaymentPage();
        this.TWACHPaymentPage = new TWACHBulkPaymentPage();
        this.CustomPaymentPage = new CustomPaymentPage();
        this.VNTaxPaymentPage = new VNTaxPaymentPage();
        this.VNLvtPage = new VNLvtPage();
        this.TWFISCPaymentPage = new TWFISCPaymentPage();
        this.PaymentLimit = new PaymentLimit();
        this.chequePaymentPage = new ChequePaymentPage();
        this.demandDraftPaymentPage = new DemandDraftPaymentPage();
        this.mt101PaymentPage = new MT101PaymentPage();
        this.selectApproverPage = new SelectApproverPage();
        this.stopChequePage = new StopChequePage();
        this.giroPaymentPage = new GiroPaymentPage();
        this.IMPSPaymentPage = new IMPSPaymentPage();
        this.BIFASTPaymentPage = new BIFASTPaymentPage();
        this.RecurringPaymentPage = new RecurringPaymentPage();
        this.singlePaymentPage = new SinglePaymentPage();
        this.eACHPaymentPage = new eACHPaymentPage();
        this.IDTAXPaymentPage = new IDTAXPaymentPage();
        this.IBPSPaymentPage = new IBPSPaymentPage();
        this.RTOLPaymentPage = new RTOLPaymentPage();
        this.IDBIFASTRequestPage = new IDBIFASTRequestPage();
    }
}
